(package "git-gutter"
         "0.92"
		 "Port of Sublime Text plugin GitGutter")

(package-file "git-gutter.el")

(website-url "https://github.com/emacsorphanage/git-gutter")
(keywords "")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "25.1")

(development
 (depends-on "elisp-lint")
 (depends-on "ert"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
